# Gemfile to help setting up the initial development environment
source 'https://rubygems.org'

gem 'calabash-common'
gem 'calabash-android', '~> 0.7'
gem 'calabash-cucumber', '~> 0.19'
gem 'sunomono', '~> 0.2'
